#declaring the type of language
language: python
   
#declaring the versions of the language specified above  you to want the test the code against
python:
  - "3.6"
   
#before executing the code installing the dependencies if any
install:
  - pip install -r requirements.txt
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - cd ta-lib
  - ./configure --prefix="/usr"
  - make
  - sudo make install
   
#running the desired code file for testing your code
script:
  - python analysis.py